# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  start-project:
    desc: start the project
    cmd: |
      cd {{.dir}}
      if [ ! -d ".terraform" ]; then
          terraform init -backend-config=backend.hcl
      fi
    silent: true
  basic-aws-s3:
    desc: basic-aws-s3 example
    vars:
      dir: 'terraform/test/basic-aws-s3'
    deps:
      - task: start-project
        vars: { dir: '{{.dir}}' }
    cmd: |
      cd {{.dir}}
      terraform {{.CLI_ARGS}}
    silent: true
  assume-role-script-test:
    desc: test assume role with aws cli
    cmds:
      - ./assume.sh
      - ./assume.sh assume
    silent: true
  env-aws-test:
    desc: test aws cli with env variables
    env:
      AWS_ACCESS_KEY_ID:
        sh: jq -r '.Credentials.AccessKeyId' credentials.json
      AWS_SECRET_ACCESS_KEY:
        sh: jq -r '.Credentials.SecretAccessKey' credentials.json
      AWS_SESSION_TOKEN:
        sh: jq -r '.Credentials.SessionToken' credentials.json
    cmds:
      - 'echo AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID'
      - 'echo AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY'
      - 'echo AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN'
    silent: true
  run-aws-cli-test:
    desc: test aws cli
    env:
      AWS_ACCESS_KEY_ID:
        sh: jq -r '.Credentials.AccessKeyId' credentials.json
      AWS_SECRET_ACCESS_KEY:
        sh: jq -r '.Credentials.SecretAccessKey' credentials.json
      AWS_SESSION_TOKEN:
        sh: jq -r '.Credentials.SessionToken' credentials.json
    cmds:
      - aws s3 ls
      - aws iam list-users
    silent: true
  basic-aws-vpc:
    desc: basic-aws-vpc example
    vars:
      dir: 'terraform/test/basic-aws-vpc'
    deps:
      - task: start-project
        vars: { dir: '{{.dir}}' }
    cmd: |
      cd {{.dir}}
      terraform {{.CLI_ARGS}}
    silent: true
  nuke-test-account:
    desc: test nuke the account
    env:
      AWS_ACCESS_KEY_ID:
        sh: jq -r '.Credentials.AccessKeyId' credentials.json
      AWS_SECRET_ACCESS_KEY:
        sh: jq -r '.Credentials.SecretAccessKey' credentials.json
      AWS_SESSION_TOKEN:
        sh: jq -r '.Credentials.SessionToken' credentials.json
    cmds:
      - cloud-nuke aws --dry-run --region mx-central-1 --config config.yaml
    silent: true
  test-account-basic-aws-vpc:
    desc: basic-aws-vpc example
    env:
      AWS_ACCESS_KEY_ID:
        sh: jq -r '.Credentials.AccessKeyId' credentials.json
      AWS_SECRET_ACCESS_KEY:
        sh: jq -r '.Credentials.SecretAccessKey' credentials.json
      AWS_SESSION_TOKEN:
        sh: jq -r '.Credentials.SessionToken' credentials.json
      AWS_DEFAULT_REGION: mx-central-1
    vars:
      dir: 'terraform/test/basic-aws-vpc'
    deps:
      - task: start-project
        vars: { dir: '{{.dir}}' }
    cmd: |
      cd {{.dir}}
      terraform {{.CLI_ARGS}}
    silent: true
  test-account-basic-aws-ec2:
    desc: basic-aws-ec2 example
    env:
      AWS_ACCESS_KEY_ID:
        sh: jq -r '.Credentials.AccessKeyId' credentials.json
      AWS_SECRET_ACCESS_KEY:
        sh: jq -r '.Credentials.SecretAccessKey' credentials.json
      AWS_SESSION_TOKEN:
        sh: jq -r '.Credentials.SessionToken' credentials.json
      AWS_DEFAULT_REGION: mx-central-1
    vars:
      dir: 'terraform/test/basic-aws-ec2'
    deps:
      - task: start-project
        vars: { dir: '{{.dir}}' }
    cmd: |
      cd {{.dir}}
      terraform {{.CLI_ARGS}}
    silent: true
  test-account-basic-aws-ec2-runner:
    desc: basic-aws-ec2-runner example
    env:
      AWS_ACCESS_KEY_ID:
        sh: jq -r '.Credentials.AccessKeyId' credentials.json
      AWS_SECRET_ACCESS_KEY:
        sh: jq -r '.Credentials.SecretAccessKey' credentials.json
      AWS_SESSION_TOKEN:
        sh: jq -r '.Credentials.SessionToken' credentials.json
      AWS_DEFAULT_REGION: mx-central-1
    vars:
      dir: 'terraform/test/basic-aws-ec2-runner'
    deps:
      - task: start-project
        vars: { dir: '{{.dir}}' }
    cmd: |
      cd {{.dir}}
      terraform {{.CLI_ARGS}}
    silent: true
  test-account-basic-aws-s3:
    desc: basic-aws-s3 example
    env:
      AWS_ACCESS_KEY_ID:
        sh: jq -r '.Credentials.AccessKeyId' credentials.json
      AWS_SECRET_ACCESS_KEY:
        sh: jq -r '.Credentials.SecretAccessKey' credentials.json
      AWS_SESSION_TOKEN:
        sh: jq -r '.Credentials.SessionToken' credentials.json
      AWS_DEFAULT_REGION: mx-central-1
    vars:
      dir: 'terraform/test/basic-aws-s3'
    deps:
      - task: start-project
        vars: { dir: '{{.dir}}' }
    cmd: |
      aws sts get-caller-identity
      cd {{.dir}}
      terraform {{.CLI_ARGS}}
    silent: true
  test-account-aws-cli-s3:
    desc: aws cli s3 example
    cmd: |
      if [[ "test" == {{.user}} ]]; then
        export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' credentials.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' credentials.json)
        export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' credentials.json)
      fi  
      aws sts get-caller-identity      
      aws s3api create-bucket --bucket {{.post}}terraform-up-and-running-state-8358497072 --region mx-central-1 --create-bucket-configuration LocationConstraint=mx-central-1
      aws s3 ls
      aws s3api head-bucket --bucket {{.post}}terraform-up-and-running-state-8358497072
      aws s3api delete-bucket --bucket {{.post}}terraform-up-and-running-state-8358497072 --region mx-central-1
    silent: true
  basic-aws-s3-test-go-with-stages:
    desc: test build with go and stages
    cmd: |
      if [[ "test" == {{.user}} ]]; then
        export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' credentials.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' credentials.json)
        export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' credentials.json)
      fi      
      aws sts get-caller-identity
      cd go
      # TF_LOG=DEBUG \
      # TF_LOG_PATH=./terraform-debug.log \
      SKIP_mock=true \
      go test -v -timeout 1m -run TestAwsS3WithStages basic_aws_s3_with_stages_test.go
    silent: true
  basic-aws-ec2-test-go-with-stages:
    desc: test build with go and stages
    cmd: |
      if [[ "test" == {{.user}} ]]; then
        export AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' credentials.json)
        export AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' credentials.json)
        export AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' credentials.json)
      fi      
      aws sts get-caller-identity
      cd go
      SKIP_mock=true \
      go test -v -timeout 5m -run TestAwsEC2WithStages basic_aws_ec2_with_stages_test.go
    silent: true

###
# NOTES
# <to run task with no env variables from the current shell>
# env -i PATH=$PATH task run-aws-cli-test
#
# <to just run to stage from a test>
# SKIP_setup=true SKIP_deploy=true SKIP_validate=true SKIP_teardown=true go test -v -run TestAwsS3WithStages
###
