name: Terraform/GO/Runner test

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # Opt in to Node.js 24 now
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: hello world
        run: echo "Hello, World!"
      # - name: request to ec2 instance
      #   run: curl http://10.0.101.49
  go-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # Opt in to Node.js 24 now
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials (assume role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/OrganizationAccountAccessRole
          # role-skip-session-tagging: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26.1'
      - name: Install dependencies
        run: |
          cd go 
          go mod tidy
      - name: Run sanity test
        run: |          
          cd go
          go test -v -timeout 30m ./sanity_test.go
      - name: Run s3 test
        run: |          
          cd go
          go test -v ./basic_aws_s3_with_stages_test.go